using DeepFoodDiary.ENTITY.Entities;
using DeepFoodDiary.ENTITY.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DeepFoodDiary.DAL.SeedData;

public class FoodSeedData : IEntityTypeConfiguration<Food>
{

    public void Configure(EntityTypeBuilder<Food> builder)
    {
       
        

        builder.HasData(
            new Food { Id = 1, CategoryId = 10000, FoodName = "Broccoli ", Calorie = 34, Protein = "2.8", Carbonhydrate = "6.6", Fat = "0.4", Measurement = 100, PortionType = PortionType.Gram},
            new Food { Id = 2, CategoryId = 10000, FoodName = "Cauliflower  ", Calorie = 25, Protein = "1.9", Carbonhydrate = "5  ", Fat = "0.3 ", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 3, CategoryId = 10000, FoodName = "Carrot", Calorie = 41, Protein = "0.9", Carbonhydrate = "9.6", Fat = "0.2", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 4, CategoryId = 10000, FoodName = "Spinach  ", Calorie = 23, Protein = "2.9", Carbonhydrate = "3.6 ", Fat = "0.4", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 5, CategoryId = 10000, FoodName = "Zucchini  ", Calorie = 17, Protein = "1.2", Carbonhydrate = "3.1 ", Fat = "0.3  ", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 6, CategoryId = 10000, FoodName = "Eggplant  ", Calorie = 25, Protein = "1", Carbonhydrate = "6", Fat = "0.2", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 7, CategoryId = 10000, FoodName = "Tomato", Calorie = 18, Protein = "0.9", Carbonhydrate = "3.9", Fat = "0.2 ", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 8, CategoryId = 10000, FoodName = "Onion", Calorie = 40, Protein = "1.1", Carbonhydrate = "9.3", Fat = "0.1", Measurement = 100, PortionType = PortionType.Gram},
            new Food { Id = 9, CategoryId = 10000, FoodName = "Mushroom", Calorie = 22, Protein = "3.1", Carbonhydrate = "3.3", Fat = "0.3", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 10, CategoryId = 10000, FoodName = "Cabbage", Calorie = 25, Protein = "1.3", Carbonhydrate = "5.8", Fat = "0.1", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 11, CategoryId = 10000, FoodName = "Brussels Sprouts ", Calorie = 43, Protein = "3.4", Carbonhydrate = "8.9 ", Fat = "0.3", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 12, CategoryId = 10000, FoodName = "Red Bell Pepper ", Calorie = 31, Protein = "1", Carbonhydrate = "6", Fat = "0.3", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 13, CategoryId = 10000, FoodName = "Green Bell Pepper ", Calorie = 20, Protein = "0.9", Carbonhydrate = "4.6", Fat = "0.2", Measurement = 100, PortionType = PortionType.Gram},
            new Food { Id = 14, CategoryId = 10000, FoodName = "Asparagus", Calorie = 20, Protein = "2.2", Carbonhydrate = "3.9", Fat = "0.1", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 15, CategoryId = 10000, FoodName = "Leeks", Calorie = 61, Protein = "1.5", Carbonhydrate = "14.2", Fat = "0.3", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 16, CategoryId = 10000, FoodName = "Celery", Calorie = 16, Protein = "0.7", Carbonhydrate = "3", Fat = "0.2", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 17, CategoryId = 10000, FoodName = "Potatoes", Calorie = 86, Protein = "1.6", Carbonhydrate = "20.1", Fat = "0.1", Measurement = 100, PortionType = PortionType.Gram},
            new Food { Id = 18, CategoryId = 10000, FoodName = "Artichokes", Calorie = 47, Protein = "3.3", Carbonhydrate = "10.5", Fat = "0.2", Measurement = 100, PortionType = PortionType.Gram},
            new Food { Id = 19, CategoryId = 10000, FoodName = "Butternut Squash", Calorie = 45, Protein = "1", Carbonhydrate = "11.7", Fat = "0.1", Measurement = 100, PortionType = PortionType.Gram},
            new Food { Id = 20, CategoryId = 10000, FoodName = "Peas", Calorie = 81, Protein = "5.4", Carbonhydrate = "14.5", Fat = "0.4", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 21, CategoryId = 10000, FoodName = "Okra", Calorie = 33, Protein = "1.9", Carbonhydrate = "7.5", Fat = "0.2", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 22, CategoryId = 10000, FoodName = "Radishes", Calorie = 16, Protein = "0.7", Carbonhydrate = "3.4", Fat = "0.1", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 23, CategoryId = 10000, FoodName = "Garlic", Calorie = 149, Protein = "6.4", Carbonhydrate = "33", Fat = "0.5", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 24, CategoryId = 10000, FoodName = "Turnips", Calorie = 28, Protein = "0.9", Carbonhydrate = "6.4", Fat = "0.1", Measurement = 100, PortionType = PortionType.Gram},
            new Food { Id = 25, CategoryId = 10000, FoodName = "Beetroot ", Calorie = 43, Protein = "1.6", Carbonhydrate = "10", Fat = "0.2", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 26, CategoryId = 10001, FoodName = "Apple", Calorie = 52, Protein = "0.3g", Carbonhydrate = "14g", Fat = "0.2g", Measurement = 1, PortionType = PortionType.UnitOrItem },
            new Food { Id = 27, CategoryId = 10001, FoodName = "Banana", Calorie = 89, Protein = "1.1g", Carbonhydrate = "23g", Fat = "0.3g", Measurement = 1, PortionType = PortionType.UnitOrItem },
            new Food { Id = 28, CategoryId = 10001, FoodName = "Cherries", Calorie = 50, Protein = "1g", Carbonhydrate = "12g", Fat = "0.3g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 29, CategoryId = 10001, FoodName = "Watermelon", Calorie = 30, Protein = "0.6g", Carbonhydrate = "8g", Fat = "0.2g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 30, CategoryId = 10001, FoodName = "Mango", Calorie = 60, Protein = "0.8g", Carbonhydrate = "15g", Fat = "0.4g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 31, CategoryId = 10001, FoodName = "Blueberries", Calorie = 57, Protein = "0.7g", Carbonhydrate = "14g", Fat = "0.3g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 32, CategoryId = 10001, FoodName = "Avocado", Calorie = 160, Protein = "2g", Carbonhydrate = "9g", Fat = "15g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 33, CategoryId = 10001, FoodName = "Peach", Calorie = 39, Protein = "0.9g", Carbonhydrate = "10g", Fat = "0.3g", Measurement = 1, PortionType = PortionType.UnitOrItem },
            new Food { Id = 34, CategoryId = 10001, FoodName = "Strawberries", Calorie = 32, Protein = "0.7g", Carbonhydrate = "8g", Fat = "0.3g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 35, CategoryId = 10001, FoodName = "Pineapple", Calorie = 50, Protein = "0.5g", Carbonhydrate = "13g", Fat = "0.1g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 36, CategoryId = 10001, FoodName = "Cantaloupe", Calorie = 34, Protein = "0.8g", Carbonhydrate = "8.2g", Fat = "0.2g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 37, CategoryId = 10001, FoodName = "Honeydew Melon", Calorie = 36, Protein = "0.5g", Carbonhydrate = "9g", Fat = "0.1g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 38, CategoryId = 10001, FoodName = "Kiwi", Calorie = 61, Protein = "1.1g", Carbonhydrate = "14.7g", Fat = "0.5g", Measurement = 1, PortionType = PortionType.UnitOrItem },
            new Food { Id = 39, CategoryId = 10001, FoodName = "Dragon Fruit", Calorie = 60, Protein = "1.2g", Carbonhydrate = "13g", Fat = "0.2g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 40, CategoryId = 10001, FoodName = "Lychee", Calorie = 66, Protein = "0.8g", Carbonhydrate = "16.5g", Fat = "0.4g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 41, CategoryId = 10001, FoodName = "Blackberries", Calorie = 43, Protein = "1.4g", Carbonhydrate = "10g", Fat = "0.5g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 42, CategoryId = 10001, FoodName = "Raspberries", Calorie = 52, Protein = "1.2g", Carbonhydrate = "12g", Fat = "0.7g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 43, CategoryId = 10001, FoodName = "Pomegranate", Calorie = 83, Protein = "1.7g", Carbonhydrate = "19g", Fat = "1.2g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 44, CategoryId = 10001, FoodName = "Passion Fruit", Calorie = 97, Protein = "2.2g", Carbonhydrate = "23g", Fat = "0.7g", Measurement = 1, PortionType = PortionType.UnitOrItem },
            new Food { Id = 45, CategoryId = 10001, FoodName = "Mangosteen", Calorie = 73, Protein = "0.5g", Carbonhydrate = "18g", Fat = "0.6g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 46, CategoryId = 10002, FoodName = "Whole Milk", Calorie = 150, Protein = "8g", Carbonhydrate = "12g", Fat = "8g", Measurement = 240, PortionType = PortionType.Glass},
            new Food { Id = 47, CategoryId = 10002, FoodName = "Plain Yogurt", Calorie = 154, Protein = "13g", Carbonhydrate = "17g", Fat = "3.5g", Measurement = 245, PortionType = PortionType.Cup },
            new Food { Id = 48, CategoryId = 10002, FoodName = "Cheddar Cheese", Calorie = 113, Protein = "7g", Carbonhydrate = "0.4g", Fat = "9g", Measurement = 28, PortionType = PortionType.Slice},
            new Food { Id = 49, CategoryId = 10002, FoodName = "Butter", Calorie = 102, Protein = "0.1g", Carbonhydrate = "0.01g", Fat = "11.5g", Measurement = 14, PortionType = PortionType.Tablesponn },
            new Food { Id = 50, CategoryId = 10002, FoodName = "Ice Cream", Calorie = 207, Protein = "3.5g", Carbonhydrate = "24g", Fat = "11g", Measurement = 100, PortionType = PortionType.Bowl },
            new Food { Id = 51, CategoryId = 10002, FoodName = "Mozzarella Cheese", Calorie = 85, Protein = "6g", Carbonhydrate = "1g", Fat = "6g", Measurement = 30, PortionType = PortionType.Slice },
            new Food { Id = 52, CategoryId = 10002, FoodName = "Cottage Cheese", Calorie = 98, Protein = "11g", Carbonhydrate = "3.4g", Fat = "4.3g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 53, CategoryId = 10002, FoodName = "Feta Cheese", Calorie = 264, Protein = "14g", Carbonhydrate = "4g", Fat = "21g", Measurement = 100, PortionType = PortionType.Gram},
            new Food { Id = 54, CategoryId = 10002, FoodName = "Skim Milk", Calorie = 83, Protein = "8g", Carbonhydrate = "12g", Fat = "0.2g", Measurement = 240, PortionType = PortionType.Glass },
            new Food { Id = 55, CategoryId = 10002, FoodName = "Almond Milk", Calorie = 30, Protein = "1g", Carbonhydrate = "1g", Fat = "2.5g", Measurement = 240, PortionType = PortionType.Glass },
            new Food { Id = 56, CategoryId = 10002, FoodName = "Greek Yogurt", Calorie = 59, Protein = "10g", Carbonhydrate = "3.6g", Fat = "0.4g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 57, CategoryId = 10002, FoodName = "Kefir", Calorie = 55, Protein = "3g", Carbonhydrate = "7g", Fat = "2g", Measurement = 240, PortionType = PortionType.Glass },
            new Food { Id = 58, CategoryId = 10002, FoodName = "Flavored Yogurt (Strawberry)", Calorie = 102, Protein = "4g", Carbonhydrate = "18g", Fat = "1.5g", Measurement = 150, PortionType = PortionType.Cup },
            new Food { Id = 59, CategoryId = 10003, FoodName = "Beef Steak", Calorie = 271, Protein = "26g", Carbonhydrate = "0g", Fat = "18g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 60, CategoryId = 10003, FoodName = "Chicken Breast", Calorie = 165, Protein = "31g", Carbonhydrate = "0g", Fat = "3.6g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 61, CategoryId = 10003, FoodName = "Pork Chop", Calorie = 231, Protein = "29g", Carbonhydrate = "0g", Fat = "13g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 62, CategoryId = 10003, FoodName = "Turkey Slices", Calorie = 135, Protein = "29g", Carbonhydrate = "3.8g", Fat = "1.7g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 63, CategoryId = 10003, FoodName = "Salami", Calorie = 336, Protein = "22g", Carbonhydrate = "2.4g", Fat = "26g", Measurement = 50, PortionType = PortionType.Slice },
            new Food { Id = 64, CategoryId = 10003, FoodName = "Bacon", Calorie = 541, Protein = "37g", Carbonhydrate = "1.4g", Fat = "42g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 65, CategoryId = 10003, FoodName = "Lamb Leg", Calorie = 291, Protein = "25g", Carbonhydrate = "0g", Fat = "21g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 66, CategoryId = 10003, FoodName = "Duck Breast", Calorie = 337, Protein = "27g", Carbonhydrate = "0g", Fat = "25g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 67, CategoryId = 10003, FoodName = "Ribeye Steak", Calorie = 271, Protein = "24g", Carbonhydrate = "0g", Fat = "19g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 68, CategoryId = 10003, FoodName = "Sirloin Steak", Calorie = 250, Protein = "26g", Carbonhydrate = "0g", Fat = "15g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 69, CategoryId = 10003, FoodName = "Ground Beef (85% lean)", Calorie = 215, Protein = "26g", Carbonhydrate = "0g", Fat = "11g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 70, CategoryId = 10003, FoodName = "Chicken Thighs", Calorie = 209, Protein = "26g", Carbonhydrate = "0g", Fat = "11g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 71, CategoryId = 10003, FoodName = "Chicken Drumsticks", Calorie = 172, Protein = "28g", Carbonhydrate = "0g", Fat = "5.7g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 72, CategoryId = 10003, FoodName = "Chicken Wings", Calorie = 203, Protein = "30g", Carbonhydrate = "0g", Fat = "8.1g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 73, CategoryId = 10003, FoodName = "Venison (Deer Meat)", Calorie = 158, Protein = "30g", Carbonhydrate = "0g", Fat = "3.2g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 74, CategoryId = 10003, FoodName = "Roast Turkey Breast", Calorie = 135, Protein = "30g", Carbonhydrate = "0g", Fat = "0.7g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 75, CategoryId = 10004, FoodName = "Salmon Fillet", Calorie = 208, Protein = "20g", Carbonhydrate = "0g", Fat = "13g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 76, CategoryId = 10004, FoodName = "Tuna Steak", Calorie = 184, Protein = "25g", Carbonhydrate = "0g", Fat = "8g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 77, CategoryId = 10004, FoodName = "Shrimp", Calorie = 99, Protein = "24g", Carbonhydrate = "0.2g", Fat = "0.3g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 78, CategoryId = 10004, FoodName = "Scallops", Calorie = 111, Protein = "21g", Carbonhydrate = "5g", Fat = "0.5g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 79, CategoryId = 10004, FoodName = "Lobster", Calorie = 89, Protein = "19g", Carbonhydrate = "0g", Fat = "0.6g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 80, CategoryId = 10004, FoodName = "Crab Meat", Calorie = 97, Protein = "21g", Carbonhydrate = "0g", Fat = "1g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 81, CategoryId = 10004, FoodName = "Cod Fillet", Calorie = 82, Protein = "18g", Carbonhydrate = "0g", Fat = "0.7g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 82, CategoryId = 10004, FoodName = "Mussels", Calorie = 172, Protein = "24g", Carbonhydrate = "7g", Fat = "4g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 83, CategoryId = 10004, FoodName = "Sardines", Calorie = 208, Protein = "25g", Carbonhydrate = "0g", Fat = "11g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 84, CategoryId = 10004, FoodName = "Haddock", Calorie = 90, Protein = "20g", Carbonhydrate = "0g", Fat = "0.7g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 85, CategoryId = 10004, FoodName = "Halibut", Calorie = 140, Protein = "27g", Carbonhydrate = "0g", Fat = "3g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 86, CategoryId = 10004, FoodName = "Oysters", Calorie = 68, Protein = "7g", Carbonhydrate = "4g", Fat = "2g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 87, CategoryId = 10004, FoodName = "Octopus", Calorie = 164, Protein = "30g", Carbonhydrate = "4g", Fat = "2g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 88, CategoryId = 10004, FoodName = "Clams", Calorie = 148, Protein = "26g", Carbonhydrate = "5g", Fat = "2g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 89, CategoryId = 10004, FoodName = "Anchovies", Calorie = 210, Protein = "29g", Carbonhydrate = "0g", Fat = "10g", Measurement = 50, PortionType = PortionType.Gram },
            new Food { Id = 90, CategoryId = 10004, FoodName = "Flounder", Calorie = 86, Protein = "18g", Carbonhydrate = "0g", Fat = "1g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 91, CategoryId = 10004, FoodName = "Sea Bass", Calorie = 97, Protein = "20g", Carbonhydrate = "0g", Fat = "2g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 92, CategoryId = 10004, FoodName = "Rainbow Trout", Calorie = 119, Protein = "20g", Carbonhydrate = "0g", Fat = "5g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 93, CategoryId = 10005, FoodName = "Lentils", Calorie = 116, Protein = "9g", Carbonhydrate = "20g", Fat = "0.4g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 94, CategoryId = 10005, FoodName = "Chickpeas", Calorie = 164, Protein = "9g", Carbonhydrate = "27g", Fat = "2.6g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 95, CategoryId = 10005, FoodName = "Black Beans", Calorie = 132, Protein = "9g", Carbonhydrate = "24g", Fat = "0.5g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 96, CategoryId = 10005, FoodName = "Kidney Beans", Calorie = 127, Protein = "9g", Carbonhydrate = "22g", Fat = "0.5g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 97, CategoryId = 10005, FoodName = "Green Peas", Calorie = 81, Protein = "5g", Carbonhydrate = "14g", Fat = "0.4g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 98, CategoryId = 10005, FoodName = "Soybeans", Calorie = 173, Protein = "17g", Carbonhydrate = "10g", Fat = "9g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 99, CategoryId = 10005, FoodName = "Navy Beans", Calorie = 140, Protein = "8g", Carbonhydrate = "26g", Fat = "0.6g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 100, CategoryId = 10005, FoodName = "Pinto Beans", Calorie = 143, Protein = "9g", Carbonhydrate = "27g", Fat = "0.6g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 101, CategoryId = 10006, FoodName = "Brown Rice", Calorie = 112, Protein = "2.6g", Carbonhydrate = "23.5g", Fat = "0.8g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 102, CategoryId = 10006, FoodName = "White Rice", Calorie = 130, Protein = "2.7g", Carbonhydrate = "28.6g", Fat = "0.3g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 103, CategoryId = 10006, FoodName = "Quinoa", Calorie = 120, Protein = "4.4g", Carbonhydrate = "21.3g", Fat = "1.9g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 104, CategoryId = 10006, FoodName = "Oats", Calorie = 389, Protein = "16.9g", Carbonhydrate = "66.3g", Fat = "6.9g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 105, CategoryId = 10006, FoodName = "Barley", Calorie = 354, Protein = "12.5g", Carbonhydrate = "73.5g", Fat = "2.3g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 106, CategoryId = 10006, FoodName = "Corn", Calorie = 86, Protein = "3.2g", Carbonhydrate = "18.7g", Fat = "1.2g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 107, CategoryId = 10006, FoodName = "Buckwheat", Calorie = 343, Protein = "13.3g", Carbonhydrate = "71.5g", Fat = "3.4g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 108, CategoryId = 10006, FoodName = "Millet", Calorie = 378, Protein = "11g", Carbonhydrate = "72.9g", Fat = "4.3g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 109, CategoryId = 10007, FoodName = "Chocolate Bar", Calorie = 546, Protein = "4.9g", Carbonhydrate = "61.7g", Fat = "31g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 110, CategoryId = 10007, FoodName = "Gummy Bears", Calorie = 325, Protein = "6.9g", Carbonhydrate = "77g", Fat = "0.2g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 111, CategoryId = 10007, FoodName = "Hard Candy", Calorie = 394, Protein = "0g", Carbonhydrate = "98g", Fat = "0g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 112, CategoryId = 10007, FoodName = "Cupcake", Calorie = 305, Protein = "2.7g", Carbonhydrate = "46.3g", Fat = "12.1g", Measurement = 1, PortionType = PortionType.UnitOrItem },
            new Food { Id = 113, CategoryId = 10007, FoodName = "Donut", Calorie = 452, Protein = "4.9g", Carbonhydrate = "51g", Fat = "25g", Measurement = 1, PortionType = PortionType.UnitOrItem },
            new Food { Id = 114, CategoryId = 10007, FoodName = "Jelly Beans", Calorie = 376, Protein = "0g", Carbonhydrate = "94g", Fat = "0g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 115, CategoryId = 10007, FoodName = "Caramel", Calorie = 382, Protein = "4.2g", Carbonhydrate = "78g", Fat = "8.3g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 116, CategoryId = 10007, FoodName = "Baklava", Calorie = 334, Protein = "5g", Carbonhydrate = "56g", Fat = "11g", Measurement = 1, PortionType = PortionType.Slice },
            new Food { Id = 117, CategoryId = 10007, FoodName = "Künefe", Calorie = 402, Protein = "9g", Carbonhydrate = "48g", Fat = "20g", Measurement = 100, PortionType = PortionType.Plate },
            new Food { Id = 118, CategoryId = 10007, FoodName = "Lokum", Calorie = 89, Protein = "0.2g", Carbonhydrate = "22g", Fat = "0g", Measurement = 1, PortionType = PortionType.UnitOrItem },
            new Food { Id = 119, CategoryId = 10007, FoodName = "Şekerpare", Calorie = 112, Protein = "1.9g", Carbonhydrate = "18.4g", Fat = "3.8g", Measurement = 1, PortionType = PortionType.UnitOrItem },
            new Food { Id = 120, CategoryId = 10007, FoodName = "Milk Chocolate", Calorie = 535, Protein = "7.6g", Carbonhydrate = "59.4g", Fat = "29.7g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 121, CategoryId = 10007, FoodName = "Dark Chocolate", Calorie = 546, Protein = "4.9g", Carbonhydrate = "61.7g", Fat = "31g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 122, CategoryId = 10007, FoodName = "White Chocolate", Calorie = 539, Protein = "6g", Carbonhydrate = "59g", Fat = "30g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 123, CategoryId = 10007, FoodName = "Tiramisu", Calorie = 240, Protein = "4g", Carbonhydrate = "24g", Fat = "15g", Measurement = 1, PortionType = PortionType.Slice },
            new Food { Id = 124, CategoryId = 10007, FoodName = "Cheesecake", Calorie = 321, Protein = "6g", Carbonhydrate = "25g", Fat = "23g", Measurement = 1, PortionType = PortionType.Slice },
            new Food { Id = 125, CategoryId = 10007, FoodName = "Macaron", Calorie = 70, Protein = "1.2g", Carbonhydrate = "9g", Fat = "3.2g", Measurement = 1, PortionType = PortionType.UnitOrItem },
            new Food { Id = 126, CategoryId = 10007, FoodName = "Cannoli", Calorie = 233, Protein = "4g", Carbonhydrate = "24g", Fat = "13g", Measurement = 1, PortionType = PortionType.UnitOrItem },
            new Food { Id = 127, CategoryId = 10008, FoodName = "Coffee, black", Calorie = 2, Protein = "0.3g", Carbonhydrate = "0g", Fat = "0g", Measurement = 240, PortionType = PortionType.Glass },
            new Food { Id = 128, CategoryId = 10008, FoodName = "Tea, brewed", Calorie = 2, Protein = "0g", Carbonhydrate = "0.3g", Fat = "0g", Measurement = 240, PortionType = PortionType.Glass },
            new Food { Id = 129, CategoryId = 10008, FoodName = "Soda", Calorie = 150, Protein = "0g", Carbonhydrate = "39g", Fat = "0g", Measurement = 355, PortionType = PortionType.Glass },
            new Food { Id = 130, CategoryId = 10008, FoodName = "Orange Juice", Calorie = 112, Protein = "1.7g", Carbonhydrate = "26g", Fat = "0.5g", Measurement = 240, PortionType = PortionType.Glass },
            new Food { Id = 131, CategoryId = 10008, FoodName = "Milk, whole", Calorie = 146, Protein = "7.9g", Carbonhydrate = "11g", Fat = "8g", Measurement = 240, PortionType = PortionType.Glass },
            new Food { Id = 132, CategoryId = 10008, FoodName = "Espresso", Calorie = 20, Protein = "0.2g", Carbonhydrate = "3g", Fat = "0.2g", Measurement = 30, PortionType = PortionType.Glass },
            new Food { Id = 133, CategoryId = 10008, FoodName = "Cappuccino", Calorie = 74, Protein = "4g", Carbonhydrate = "6g", Fat = "4g", Measurement = 150, PortionType = PortionType.Glass },
            new Food { Id = 134, CategoryId = 10008, FoodName = "Latte Macchiato", Calorie = 135, Protein = "8g", Carbonhydrate = "12g", Fat = "7g", Measurement = 240, PortionType = PortionType.Glass },
            new Food { Id = 135, CategoryId = 10008, FoodName = "Iced Coffee", Calorie = 50, Protein = "0.3g", Carbonhydrate = "12g", Fat = "0.1g", Measurement = 240, PortionType = PortionType.Glass },
            new Food { Id = 136, CategoryId = 10008, FoodName = "Green Tea", Calorie = 0, Protein = "0g", Carbonhydrate = "0g", Fat = "0g", Measurement = 240, PortionType = PortionType.Glass },
            new Food { Id = 137, CategoryId = 10008, FoodName = "Black Tea", Calorie = 2, Protein = "0g", Carbonhydrate = "0.3g", Fat = "0g", Measurement = 240, PortionType = PortionType.Glass },
            new Food { Id = 138, CategoryId = 10008, FoodName = "Herbal Tea", Calorie = 2, Protein = "0g", Carbonhydrate = "0.5g", Fat = "0g", Measurement = 240, PortionType = PortionType.Glass },
            new Food { Id = 139, CategoryId = 10008, FoodName = "Chai Latte", Calorie = 120, Protein = "4g", Carbonhydrate = "22g", Fat = "2.5g", Measurement = 240, PortionType = PortionType.Glass },
            new Food { Id = 140, CategoryId = 10008, FoodName = "Mineral Water", Calorie = 0, Protein = "0g", Carbonhydrate = "0g", Fat = "0g", Measurement = 330, PortionType = PortionType.Glass },
            new Food { Id = 141, CategoryId = 10008, FoodName = "Flavored Sparkling Water, Lemon", Calorie = 10, Protein = "0g", Carbonhydrate = "2g", Fat = "0g", Measurement = 330, PortionType = PortionType.Glass },
            new Food { Id = 142, CategoryId = 10008, FoodName = "Flavored Sparkling Water, Lime", Calorie = 10, Protein = "0g", Carbonhydrate = "2g", Fat = "0g", Measurement = 330, PortionType = PortionType.Glass },
            new Food { Id = 143, CategoryId = 10009, FoodName = "Chicken Noodle Soup", Calorie = 75, Protein = "4.5g", Carbonhydrate = "8.5g", Fat = "2.5g", Measurement = 240, PortionType = PortionType.Bowl },
            new Food { Id = 144, CategoryId = 10009, FoodName = "Tomato Soup", Calorie = 85, Protein = "1.5g", Carbonhydrate = "18.6g", Fat = "0.4g", Measurement = 240, PortionType = PortionType.Bowl },
            new Food { Id = 145, CategoryId = 10009, FoodName = "Beef Stew", Calorie = 160, Protein = "11g", Carbonhydrate = "15g", Fat = "7g", Measurement = 240, PortionType = PortionType.Bowl },
            new Food { Id = 146, CategoryId = 10009, FoodName = "Minestrone", Calorie = 90, Protein = "3g", Carbonhydrate = "17g", Fat = "1g", Measurement = 240, PortionType = PortionType.Bowl },
            new Food { Id = 147, CategoryId = 10009, FoodName = "Clam Chowder", Calorie = 201, Protein = "16g", Carbonhydrate = "21g", Fat = "8g", Measurement = 240, PortionType = PortionType.Bowl },
            new Food { Id = 148, CategoryId = 10009, FoodName = "Lentil Soup", Calorie = 180, Protein = "12g", Carbonhydrate = "30g", Fat = "1g", Measurement = 240, PortionType = PortionType.Bowl },
            new Food { Id = 149, CategoryId = 10009, FoodName = "Broccoli Cheese Soup", Calorie = 206, Protein = "10g", Carbonhydrate = "16.5g", Fat = "12.5g", Measurement = 240, PortionType = PortionType.Bowl },
            new Food { Id = 150, CategoryId = 10009, FoodName = "French Onion Soup", Calorie = 224, Protein = "8g", Carbonhydrate = "17g", Fat = "14g", Measurement = 240, PortionType = PortionType.Bowl },
            new Food { Id = 151, CategoryId = 10009, FoodName = "Mercimek Soup", Calorie = 180, Protein = "9g", Carbonhydrate = "20g", Fat = "7g", Measurement = 240, PortionType = PortionType.Bowl },
            new Food { Id = 152, CategoryId = 10009, FoodName = "Ezogelin Soup", Calorie = 165, Protein = "5g", Carbonhydrate = "25g", Fat = "5g", Measurement = 240, PortionType = PortionType.Bowl },
            new Food { Id = 153, CategoryId = 10009, FoodName = "İşkembe Soup", Calorie = 90, Protein = "12g", Carbonhydrate = "3g", Fat = "4g", Measurement = 240, PortionType = PortionType.Bowl },
            new Food { Id = 154, CategoryId = 10009, FoodName = "Yayla Soup", Calorie = 140, Protein = "6g", Carbonhydrate = "18g", Fat = "6g", Measurement = 240, PortionType = PortionType.Bowl },
            new Food { Id = 155, CategoryId = 10009, FoodName = "Tarhana Soup", Calorie = 150, Protein = "5g", Carbonhydrate = "25g", Fat = "3g", Measurement = 240, PortionType = PortionType.Bowl },
            new Food { Id = 156, CategoryId = 10009, FoodName = "Tavuk Suyu Soup", Calorie = 75, Protein = "6g", Carbonhydrate = "8g", Fat = "2g", Measurement = 240, PortionType = PortionType.Bowl },
            new Food { Id = 157, CategoryId = 10009, FoodName = "Paça Soup", Calorie = 200, Protein = "14g", Carbonhydrate = "0g", Fat = "15g", Measurement = 240, PortionType = PortionType.Bowl },
            new Food { Id = 158, CategoryId = 10010, FoodName = "Whole Wheat Bread", Calorie = 100, Protein = "4g", Carbonhydrate = "20g", Fat = "2g", Measurement = 1, PortionType = PortionType.Slice },
            new Food { Id = 159, CategoryId = 10010, FoodName = "Baguette", Calorie = 175, Protein = "6g", Carbonhydrate = "36g", Fat = "1g", Measurement = 58, PortionType = PortionType.Slice },
            new Food { Id = 160, CategoryId = 10010, FoodName = "Croissant", Calorie = 235, Protein = "5g", Carbonhydrate = "26g", Fat = "12g", Measurement = 1, PortionType = PortionType.UnitOrItem },
            new Food { Id = 161, CategoryId = 10010, FoodName = "Cinnamon Roll", Calorie = 303, Protein = "5g", Carbonhydrate = "41g", Fat = "13g", Measurement = 1, PortionType = PortionType.UnitOrItem },
            new Food { Id = 162, CategoryId = 10010, FoodName = "Sourdough Bread", Calorie = 170, Protein = "6g", Carbonhydrate = "33g", Fat = "1g", Measurement = 2, PortionType = PortionType.Slice },
            new Food { Id = 163, CategoryId = 10010, FoodName = "Muffin", Calorie = 377, Protein = "5g", Carbonhydrate = "51g", Fat = "17g", Measurement = 1, PortionType = PortionType.UnitOrItem },
            new Food { Id = 164, CategoryId = 10010, FoodName = "Pita Bread", Calorie = 165, Protein = "5.5g", Carbonhydrate = "33g", Fat = "0.7g", Measurement = 1, PortionType = PortionType.UnitOrItem },
            new Food { Id = 165, CategoryId = 10010, FoodName = "Rye Bread", Calorie = 83, Protein = "2.7g", Carbonhydrate = "15.5g", Fat = "0.8g", Measurement = 1, PortionType = PortionType.Slice },
            new Food { Id = 166, CategoryId = 10010, FoodName = "Brioche", Calorie = 300, Protein = "6g", Carbonhydrate = "52g", Fat = "8g", Measurement = 1, PortionType = PortionType.UnitOrItem },
            new Food { Id = 167, CategoryId = 10010, FoodName = "Focaccia", Calorie = 142, Protein = "2.7g", Carbonhydrate = "27g", Fat = "2.3g", Measurement = 1, PortionType = PortionType.Slice },
            new Food { Id = 168, CategoryId = 10010, FoodName = "Garlic Bread", Calorie = 180, Protein = "5g", Carbonhydrate = "27g", Fat = "7g", Measurement = 1, PortionType = PortionType.Slice },
            new Food { Id = 169, CategoryId = 10010, FoodName = "Crackers", Calorie = 120, Protein = "2g", Carbonhydrate = "20g", Fat = "3.5g", Measurement = 30, PortionType = PortionType.Gram },
            new Food { Id = 170, CategoryId = 10010, FoodName = "Pretzels", Calorie = 108, Protein = "2.8g", Carbonhydrate = "22.5g", Fat = "0.8g", Measurement = 1, PortionType = PortionType.UnitOrItem },
            new Food { Id = 171, CategoryId = 10010, FoodName = "Melba Toast", Calorie = 79, Protein = "2.6g", Carbonhydrate = "14.2g", Fat = "0.8g", Measurement = 4, PortionType = PortionType.Slice },
            new Food { Id = 172, CategoryId = 10010, FoodName = "Croissant, Almond", Calorie = 410, Protein = "10g", Carbonhydrate = "45g", Fat = "23g", Measurement = 1, PortionType = PortionType.UnitOrItem },
            new Food { Id = 173, CategoryId = 10010, FoodName = "Simit", Calorie = 290, Protein = "10g", Carbonhydrate = "55g", Fat = "3.6g", Measurement = 1, PortionType = PortionType.UnitOrItem },
            new Food { Id = 174, CategoryId = 10011, FoodName = "Black Pepper", Calorie = 255, Protein = "10g", Carbonhydrate = "64g", Fat = "3.3g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 175, CategoryId = 10011, FoodName = "Turmeric", Calorie = 312, Protein = "9.7g", Carbonhydrate = "67.1g", Fat = "3.3g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 176, CategoryId = 10011, FoodName = "Ketchup", Calorie = 112, Protein = "1.2g", Carbonhydrate = "27g", Fat = "0.1g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 177, CategoryId = 10011, FoodName = "Mayonnaise", Calorie = 680, Protein = "1g", Carbonhydrate = "2g", Fat = "75g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 178, CategoryId = 10011, FoodName = "Cinnamon", Calorie = 247, Protein = "4g", Carbonhydrate = "81g", Fat = "1.2g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 179, CategoryId = 10011, FoodName = "Soy Sauce", Calorie = 53, Protein = "4.9g", Carbonhydrate = "4.9g", Fat = "0.6g", Measurement = 100, PortionType = PortionType.Milliliter },
            new Food { Id = 180, CategoryId = 10011, FoodName = "Hot Sauce", Calorie = 30, Protein = "1g", Carbonhydrate = "7g", Fat = "0.2g", Measurement = 100, PortionType = PortionType.Milliliter },
            new Food { Id = 181, CategoryId = 10011, FoodName = "Curry Powder", Calorie = 325, Protein = "14g", Carbonhydrate = "58g", Fat = "14g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 182, CategoryId = 10012, FoodName = "Potato Chips", Calorie = 547, Protein = "6.6g", Carbonhydrate = "51.4g", Fat = "36.4g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 183, CategoryId = 10012, FoodName = "Mixed Nuts", Calorie = 607, Protein = "17g", Carbonhydrate = "20g", Fat = "54g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 184, CategoryId = 10012, FoodName = "Popcorn, Air-popped", Calorie = 387, Protein = "13g", Carbonhydrate = "78g", Fat = "4.5g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 185, CategoryId = 10012, FoodName = "Trail Mix", Calorie = 462, Protein = "13g", Carbonhydrate = "56g", Fat = "26g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 186, CategoryId = 10012, FoodName = "Fruit Snacks", Calorie = 325, Protein = "0g", Carbonhydrate = "76g", Fat = "0g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 187, CategoryId = 10012, FoodName = "Granola Bar", Calorie = 471, Protein = "10g", Carbonhydrate = "64g", Fat = "21g", Measurement = 1, PortionType = PortionType.UnitOrItem },
            new Food { Id = 188, CategoryId = 10012, FoodName = "Rice Cake", Calorie = 387, Protein = "8.4g", Carbonhydrate = "81.3g", Fat = "3.3g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 189, CategoryId = 10012, FoodName = "Vegetable Chips", Calorie = 472, Protein = "2.5g", Carbonhydrate = "62.5g", Fat = "25g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 190, CategoryId = 10012, FoodName = "Cheese Puffs", Calorie = 536, Protein = "7.6g", Carbonhydrate = "50g", Fat = "34g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 191, CategoryId = 10012, FoodName = "Beef Jerky", Calorie = 410, Protein = "33g", Carbonhydrate = "11g", Fat = "27g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 192, CategoryId = 10012, FoodName = "Almond Butter", Calorie = 614, Protein = "21g", Carbonhydrate = "20g", Fat = "56g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 193, CategoryId = 10012, FoodName = "Peanut Butter Cups", Calorie = 515, Protein = "10g", Carbonhydrate = "59g", Fat = "30g", Measurement = 1, PortionType = PortionType.UnitOrItem },
            new Food { Id = 194, CategoryId = 10012, FoodName = "Sunflower Seeds", Calorie = 584, Protein = "20g", Carbonhydrate = "20g", Fat = "51g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 195, CategoryId = 10012, FoodName = "Hummus", Calorie = 177, Protein = "8g", Carbonhydrate = "14g", Fat = "10g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 196, CategoryId = 10012, FoodName = "Yogurt-Covered Raisins", Calorie = 320, Protein = "2.8g", Carbonhydrate = "70g", Fat = "7.5g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 197, CategoryId = 10013, FoodName = "Light Beer", Calorie = 103, Protein = "1g", Carbonhydrate = "6g", Fat = "0g", Measurement = 355, PortionType = PortionType.Glass },
            new Food { Id = 198, CategoryId = 10013, FoodName = "Red Wine", Calorie = 125, Protein = "0.1g", Carbonhydrate = "3.8g", Fat = "0g", Measurement = 150, PortionType = PortionType.Glass },
            new Food { Id = 199, CategoryId = 10013, FoodName = "Vodka", Calorie = 231, Protein = "0g", Carbonhydrate = "0g", Fat = "0g", Measurement = 100, PortionType = PortionType.Glass },
            new Food { Id = 200, CategoryId = 10013, FoodName = "Whiskey", Calorie = 70, Protein = "0g", Carbonhydrate = "0g", Fat = "0g", Measurement = 45, PortionType = PortionType.Glass },
            new Food { Id = 201, CategoryId = 10013, FoodName = "Gin", Calorie = 263, Protein = "0g", Carbonhydrate = "0g", Fat = "0g", Measurement = 100, PortionType = PortionType.Glass },
            new Food { Id = 202, CategoryId = 10013, FoodName = "Champagne", Calorie = 87, Protein = "0.3g", Carbonhydrate = "1.4g", Fat = "0g", Measurement = 150, PortionType = PortionType.Glass },
            new Food { Id = 203, CategoryId = 10013, FoodName = "Margarita", Calorie = 168, Protein = "0g", Carbonhydrate = "11g", Fat = "0g", Measurement = 120, PortionType = PortionType.Glass },
            new Food { Id = 204, CategoryId = 10013, FoodName = "Rum", Calorie = 231, Protein = "0g", Carbonhydrate = "0g", Fat = "0g", Measurement = 100, PortionType = PortionType.Glass },
            new Food { Id = 205, CategoryId = 10014, FoodName = "Caesar Salad", Calorie = 180, Protein = "7g", Carbonhydrate = "10g", Fat = "14g", Measurement = 100, PortionType = PortionType.Plate },
            new Food { Id = 206, CategoryId = 10014, FoodName = "Greek Salad", Calorie = 106, Protein = "2.9g", Carbonhydrate = "4.3g", Fat = "8.4g", Measurement = 100, PortionType = PortionType.Plate },
            new Food { Id = 207, CategoryId = 10014, FoodName = "Caprese Salad", Calorie = 200, Protein = "8g", Carbonhydrate = "5g", Fat = "16g", Measurement = 100, PortionType = PortionType.Plate },
            new Food { Id = 208, CategoryId = 10014, FoodName = "Waldorf Salad", Calorie = 160, Protein = "2g", Carbonhydrate = "15g", Fat = "10g", Measurement = 100, PortionType = PortionType.Plate },
            new Food { Id = 209, CategoryId = 10014, FoodName = "Cobb Salad", Calorie = 233, Protein = "13g", Carbonhydrate = "9g", Fat = "16g", Measurement = 100, PortionType = PortionType.Plate },
            new Food { Id = 210, CategoryId = 10014, FoodName = "Nicoise Salad", Calorie = 105, Protein = "7g", Carbonhydrate = "3g", Fat = "7g", Measurement = 100, PortionType = PortionType.Plate },
            new Food { Id = 211, CategoryId = 10014, FoodName = "Quinoa Salad", Calorie = 120, Protein = "4g", Carbonhydrate = "20g", Fat = "3.5g", Measurement = 100, PortionType = PortionType.Plate },
            new Food { Id = 212, CategoryId = 10014, FoodName = "Southwest Chicken Salad", Calorie = 290, Protein = "24g", Carbonhydrate = "22g", Fat = "12g", Measurement = 100, PortionType = PortionType.Plate },
            new Food { Id = 213, CategoryId = 10015, FoodName = "Turkish Kebab", Calorie = 250, Protein = "22g", Carbonhydrate = "5g", Fat = "15g", Measurement = 1, PortionType = PortionType.Plate },
            new Food { Id = 214, CategoryId = 10015, FoodName = "Italian Pizza Margherita", Calorie = 270, Protein = "11g", Carbonhydrate = "34g", Fat = "10g", Measurement = 1, PortionType = PortionType.Slice },
            new Food { Id = 215, CategoryId = 10015, FoodName = "Japanese Sushi Roll", Calorie = 200, Protein = "6g", Carbonhydrate = "42g", Fat = "1g", Measurement = 8, PortionType = PortionType.UnitOrItem },
            new Food { Id = 216, CategoryId = 10015, FoodName = "Indian Chicken Curry", Calorie = 260, Protein = "25g", Carbonhydrate = "10g", Fat = "14g", Measurement = 100, PortionType = PortionType.Plate },
            new Food { Id = 217, CategoryId = 10015, FoodName = "Mexican Tacos", Calorie = 156, Protein = "9g", Carbonhydrate = "12g", Fat = "8g", Measurement = 1, PortionType = PortionType.UnitOrItem },
            new Food { Id = 218, CategoryId = 10015, FoodName = "French Ratatouille", Calorie = 90, Protein = "1.2g", Carbonhydrate = "20g", Fat = "0.4g", Measurement = 100, PortionType = PortionType.Plate },
            new Food { Id = 219, CategoryId = 10015, FoodName = "American Burger", Calorie = 295, Protein = "17g", Carbonhydrate = "30g", Fat = "11g", Measurement = 1, PortionType = PortionType.UnitOrItem },
            new Food { Id = 220, CategoryId = 10015, FoodName = "Greek Moussaka", Calorie = 150, Protein = "8g", Carbonhydrate = "18g", Fat = "7g", Measurement = 100, PortionType = PortionType.Plate },
            new Food { Id = 221, CategoryId = 10015, FoodName = "Chinese Fried Rice", Calorie = 238, Protein = "5.6g", Carbonhydrate = "38.3g", Fat = "7.3g", Measurement = 100, PortionType = PortionType.Plate },
            new Food { Id = 222, CategoryId = 10015, FoodName = "Turkish Menemen", Calorie = 200, Protein = "12g", Carbonhydrate = "10g", Fat = "14g", Measurement = 100, PortionType = PortionType.Plate },
            new Food { Id = 223, CategoryId = 10015, FoodName = "Spanish Paella", Calorie = 280, Protein = "22g", Carbonhydrate = "31g", Fat = "7g", Measurement = 100, PortionType = PortionType.Plate },
            new Food { Id = 224, CategoryId = 10015, FoodName = "Moroccan Tagine", Calorie = 310, Protein = "35g", Carbonhydrate = "30g", Fat = "9g", Measurement = 100, PortionType = PortionType.Plate },
            new Food { Id = 225, CategoryId = 10015, FoodName = "German Schnitzel", Calorie = 330, Protein = "25g", Carbonhydrate = "18g", Fat = "18g", Measurement = 100, PortionType = PortionType.Plate },
            new Food { Id = 226, CategoryId = 10015, FoodName = "Turkish İmam Bayıldı", Calorie = 150, Protein = "3g", Carbonhydrate = "20g", Fat = "8g", Measurement = 1, PortionType = PortionType.UnitOrItem },
            new Food { Id = 227, CategoryId = 10015, FoodName = "Vietnamese Pho", Calorie = 450, Protein = "30g", Carbonhydrate = "40g", Fat = "15g", Measurement = 1, PortionType = PortionType.Bowl },
            new Food { Id = 228, CategoryId = 10015, FoodName = "Italian Lasagna", Calorie = 280, Protein = "17g", Carbonhydrate = "31g", Fat = "13g", Measurement = 100, PortionType = PortionType.Plate },
            new Food { Id = 229, CategoryId = 10015, FoodName = "Korean Bibimbap", Calorie = 560, Protein = "22g", Carbonhydrate = "84g", Fat = "18g", Measurement = 1, PortionType = PortionType.Bowl },
            new Food { Id = 230, CategoryId = 10015, FoodName = "Ethiopian Doro Wat", Calorie = 240, Protein = "28g", Carbonhydrate = "10g", Fat = "10g", Measurement = 1, PortionType = PortionType.Plate },
            new Food { Id = 231, CategoryId = 10015, FoodName = "Brazilian Feijoada", Calorie = 340, Protein = "25g", Carbonhydrate = "30g", Fat = "15g", Measurement = 100, PortionType = PortionType.Plate },
            new Food { Id = 232, CategoryId = 10015, FoodName = "Classic Breakfast Burger", Calorie = 550, Protein = "28g", Carbonhydrate = "40g", Fat = "30g", Measurement = 1, PortionType = PortionType.UnitOrItem },
            new Food { Id = 233, CategoryId = 10015, FoodName = "Egg and Bacon Breakfast Burger", Calorie = 600, Protein = "35g", Carbonhydrate = "40g", Fat = "35g", Measurement = 1, PortionType = PortionType.UnitOrItem },
            new Food { Id = 234, CategoryId = 10015, FoodName = "Avocado and Turkey Breakfast Burger", Calorie = 500, Protein = "30g", Carbonhydrate = "45g", Fat = "25g", Measurement = 1, PortionType = PortionType.UnitOrItem },
            new Food { Id = 235, CategoryId = 10015, FoodName = "Vegetarian Breakfast Burger", Calorie = 400, Protein = "18g", Carbonhydrate = "50g", Fat = "18g", Measurement = 1, PortionType = PortionType.UnitOrItem },
            new Food { Id = 236, CategoryId = 10015, FoodName = "Spicy Chorizo Breakfast Burger", Calorie = 650, Protein = "32g", Carbonhydrate = "40g", Fat = "40g", Measurement = 1, PortionType = PortionType.UnitOrItem },
            new Food { Id = 237, CategoryId = 10016, FoodName = "Porridge", Calorie = 102, Protein = "2.5g", Carbonhydrate = "19g", Fat = "1.7g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 238, CategoryId = 10016, FoodName = "Granola", Calorie = 471, Protein = "10g", Carbonhydrate = "64g", Fat = "21g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 239, CategoryId = 10016, FoodName = "Boiled Eggs", Calorie = 155, Protein = "13g", Carbonhydrate = "1.1g", Fat = "11g", Measurement = 2, PortionType = PortionType.UnitOrItem },
            new Food { Id = 240, CategoryId = 10016, FoodName = "French Toast", Calorie = 149, Protein = "5g", Carbonhydrate = "22g", Fat = "4.5g", Measurement = 1, PortionType = PortionType.Slice },
            new Food { Id = 241, CategoryId = 10016, FoodName = "Turkey Sausage", Calorie = 149, Protein = "17g", Carbonhydrate = "0.7g", Fat = "8.3g", Measurement = 1, PortionType = PortionType.UnitOrItem },
            new Food { Id = 242, CategoryId = 10016, FoodName = "Olive", Calorie = 115, Protein = "0.8g", Carbonhydrate = "6g", Fat = "10.7g", Measurement = 10, PortionType = PortionType.UnitOrItem },
            new Food { Id = 243, CategoryId = 10016, FoodName = "Honey", Calorie = 304, Protein = "0.3g", Carbonhydrate = "82.4g", Fat = "0g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 244, CategoryId = 10016, FoodName = "Whole Wheat Waffles", Calorie = 205, Protein = "6g", Carbonhydrate = "30g", Fat = "7g", Measurement = 1, PortionType = PortionType.UnitOrItem },
            new Food { Id = 245, CategoryId = 10016, FoodName = "Cornflakes", Calorie = 357, Protein = "7.5g", Carbonhydrate = "84g", Fat = "0.4g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 246, CategoryId = 10016, FoodName = "Breakfast Burrito", Calorie = 217, Protein = "12g", Carbonhydrate = "24g", Fat = "9g", Measurement = 1, PortionType = PortionType.UnitOrItem },
            new Food { Id = 247, CategoryId = 10016, FoodName = "Gözleme", Calorie = 289, Protein = "9g", Carbonhydrate = "34g", Fat = "13g", Measurement = 1, PortionType = PortionType.UnitOrItem },
            new Food { Id = 248, CategoryId = 10016, FoodName = "Börek", Calorie = 275, Protein = "8g", Carbonhydrate = "25g", Fat = "16g", Measurement = 1, PortionType = PortionType.Slice },
            new Food { Id = 249, CategoryId = 10016, FoodName = "Bagels", Calorie = 250, Protein = "10g", Carbonhydrate = "50g", Fat = "1.5g", Measurement = 1, PortionType = PortionType.UnitOrItem },
            new Food { Id = 250, CategoryId = 10016, FoodName = "Ricotta Pancakes", Calorie = 209, Protein = "11g", Carbonhydrate = "26g", Fat = "7g", Measurement = 3, PortionType = PortionType.UnitOrItem },
            new Food { Id = 251, CategoryId = 10016, FoodName = "Fruit Muesli", Calorie = 289, Protein = "6g", Carbonhydrate = "66g", Fat = "4g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 252, CategoryId = 10016, FoodName = "Poached Eggs", Calorie = 143, Protein = "12g", Carbonhydrate = "0.7g", Fat = "9.5g", Measurement = 2, PortionType = PortionType.UnitOrItem },
            new Food { Id = 253, CategoryId = 10016, FoodName = "Cottage Cheese with Pineapple", Calorie = 97, Protein = "11g", Carbonhydrate = "10g", Fat = "1g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 254, CategoryId = 10016, FoodName = "Chia Seed Pudding", Calorie = 134, Protein = "4g", Carbonhydrate = "13g", Fat = "8g", Measurement = 100, PortionType = PortionType.Gram },
            new Food { Id = 255, CategoryId = 10016, FoodName = "English Muffin with Egg and Cheese", Calorie = 360, Protein = "19g", Carbonhydrate = "29g", Fat = "19g", Measurement = 1, PortionType = PortionType.UnitOrItem }
            );
    }
}
